# This is a basic workflow to help you get started with Actions

name: cloneremoterepo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: PowerShell script
        # You may pin to the exact commit or the version.
        # uses: Amadevus/pwsh-script@97a8b211a5922816aa8a69ced41fa32f23477186
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          # PowerShell script to execute in Actions-hydrated context
          script: |
            echo "nada"
         

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          echo "****************************"
          $rama = 
          #cd "D:\temp\remoterepo"
          git fetch
          git checkout -b $env.rama
          git pull
          echo ${{ github.ref_name	}}
          echo ${{ github.run_number }}
          echo "workspace"- ${{ github.workspace }}
          echo "push on branch ${{ github.ref_name	}} with id ${{ github.run_number }}"
          echo "****************************"
          cd ${{ github.workspace }}
          #Get-ChildItem -Path .\ -Exclude .github | Copy-Item -Destination "D:\temp\remoterepo" -Recurse -Force
          #Get-ChildItem -Path .\ | Copy-Item -Destination "D:\temp\remoterepo" -Recurse -Force
          cd "D:\temp\remoterepo"
          
          git add .
          git pull
          git status
          git commit -am  "test commit"
          git remote -v 
          git push 
          
      # cd "C:\GitHub\actions-runner\_work\synapse\synapse"
          
